apiVersion: v1
kind: PersistentVolume
metadata:
  name: flight-pv
spec:
  storageClassName: flightstorage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/db/data
