apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flight-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: flightstorage
  resources:
    requests:
      storage: 10Gi

